# Generated by Django 4.2.1 on 2023-06-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_portfolio_homepage_services_homepage_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="team",
        ),
    ]
