# Generated by Django 4.2.1 on 2023-06-06 10:16

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_homepage_myteam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="myteam",
            field=wagtail.fields.StreamField(
                [
                    (
                        "myteam",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "photo",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                (
                                    "name",
                                    wagtail.blocks.CharBlock(form_classname="name"),
                                ),
                                ("intro", wagtail.blocks.RichTextBlock()),
                                (
                                    "designation",
                                    wagtail.blocks.CharBlock(
                                        form_classname="designation"
                                    ),
                                ),
                                (
                                    "socialMedia",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("instagram", wagtail.blocks.CharBlock()),
                                            ("linked_in", wagtail.blocks.CharBlock()),
                                            ("git", wagtail.blocks.CharBlock()),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
