# Generated by Django 4.2.2 on 2023-06-27 08:05

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_homepage_from_address_homepage_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="thank_you_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
