# Generated by Django 4.2.2 on 2023-07-02 08:51

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_homepage_thank_you_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="myteam",
            field=wagtail.fields.StreamField(
                [
                    (
                        "myteam",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "photo",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                (
                                    "name",
                                    wagtail.blocks.CharBlock(form_classname="name"),
                                ),
                                ("intro", wagtail.blocks.RichTextBlock()),
                                (
                                    "designation",
                                    wagtail.blocks.CharBlock(
                                        form_classname="designation"
                                    ),
                                ),
                                (
                                    "socialMedia",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "instagram",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "linked_in",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "git",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
