# Generated by Django 4.2.1 on 2023-07-03 07:16

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_homepage_myteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='heading',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
